<?php

/**
 * @file
 * Module file.
 */

include_once 'includes/nexteuropa_integration_producer.entity.inc';
include_once 'includes/nexteuropa_integration_producer.hooks.inc';

/**
 * Collect and return list of producer definitions.
 *
 * @return array
 *    List of producer definitions.
 */
function nexteuropa_integration_producer_get_producer_info() {
  $producers = module_invoke_all('nexteuropa_integration_producer_info');
  drupal_alter('nexteuropa_integration_producer_info', $producers);
  return $producers;
}

/**
 * Collect and return list of producer field handler definitions.
 *
 * @return array
 *    List of producer field handler definitions.
 */
function nexteuropa_integration_producer_get_field_handler_info() {
  $field_handlers = module_invoke_all('nexteuropa_integration_producer_field_handler_info');
  drupal_alter('nexteuropa_integration_producer_field_handler_info', $field_handlers);
  return $field_handlers;
}
