<?php

/**
 * @file
 * Integration Layer plugin for NextEuropa.
 */

/**
 * Implements hook_nexteuropa_integration_producer_info().
 */
function nexteuropa_integration_nexteuropa_integration_producer_info() {
  $prefix = '\Drupal\nexteuropa_integration\Producer';
  return array(
    'node'          => array('class' => $prefix . '\NodeProducer'),
    'taxonomy_term' => array('class' => $prefix . '\TaxonomyTermProducer'),
  );
}

/**
 * Implements hook_nexteuropa_integration_producer_info().
 */
function nexteuropa_integration_nexteuropa_integration_producer_field_handler_info() {
  $prefix = '\Drupal\nexteuropa_integration\Producer\FieldHandlers';
  return array(
    'default'           => array('class' => $prefix . '\DefaultFieldHandler'),
    'text'              => array('class' => $prefix . '\TextFieldHandler'),
    'text_long'         => array('class' => $prefix . '\TextFieldHandler'),
    'text_with_summary' => array('class' => $prefix . '\TextWithSummaryFieldHandler'),
    'date'              => array('class' => $prefix . '\DateFieldHandler'),
    'datetime'          => array('class' => $prefix . '\DateFieldHandler'),
    'datestamp'         => array('class' => $prefix . '\DateFieldHandler'),
    'file'              => array('class' => $prefix . '\FileFieldHandler'),
    'image'             => array('class' => $prefix . '\FileFieldHandler'),
  );
}

/**
 * Collect and return list of producer field handler definitions.
 *
 * @return array
 *    List of producer field handler definitions.
 */
function nexteuropa_integration_producer_info_field_handlers() {
  $field_handlers = module_invoke_all('nexteuropa_integration_producer_field_handler_info');
  drupal_alter('nexteuropa_integration_producer_field_handler_info', $field_handlers);
  return $field_handlers;
}

/**
 * Collect and return list of producer definitions.
 *
 * @return array
 *    List of producer definitions.
 */
function nexteuropa_integration_producer_info_producers() {
  $producers = module_invoke_all('nexteuropa_integration_producer_info');
  drupal_alter('nexteuropa_integration_producer_info', $producers);
  return $producers;
}
